Repository openshift/configure-goalert-operator, pull requests merged in 2023-05, with the labels that each got.

#3 Set up grapql api calls and controller part I
  PROJECT
  api/v1alpha1/goalertintegration_types.go
  api/v1alpha1/groupversion_info.go
  config/config.go
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_goalertintegrations.yaml
  config/crd/patches/webhook_in_goalertintegrations.yaml
  config/rbac/goalertintegration_editor_role.yaml
  config/rbac/goalertintegration_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/goalert.openshift.io_v1alpha1_goalertintegration.yaml
  config/samples/kustomization.yaml
  controllers/goalertintegration/clusterdeployment_created.go
  controllers/goalertintegration/clusterdeployment_deleted.go
  controllers/goalertintegration/goalertintegration_controller.go
  controllers/goalertintegration/suite_test.go
  controllers/goalertintegration_controller.go
  deploy/crds/goalert.openshift.io.managed.openshift.io_goalertintegrations.yaml
  main.go
  pkg/goalert/service.go
  pkg/utils/secrets.go
Labels: lgtm, tide/merge-method-squash

#7 handle create svc in goalert
  config/config.go
  controllers/goalertintegration/clusterdeployment_created.go
  controllers/goalertintegration/goalertintegration_controller.go
  pkg/goalert/service.go
  pkg/kube/configmap.go
  pkg/kube/syncset.go
Labels: approved, lgtm

#9 Fix docker build and prow testing
  .gitignore
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.openapi.go
  build/Dockerfile
  build/Dockerfile.olm-registry
  config/config.go
  controllers/goalertintegration/clusterdeployment_created.go
  controllers/goalertintegration/clusterdeployment_deleted.go
  controllers/goalertintegration/goalertintegration_controller.go
  deploy/crds/goalert.managed.openshift.io_goalertintegrations.yaml
  go.mod
  go.sum
  main.go
  pkg/goalert/service.go
  pkg/kube/syncset.go
Labels: approved, lgtm, tide/merge-method-squash
